remote_theme: pmarsceill/just-the-docs

title: Matt DiPietro
description: a brief guide to me as a co-worker, manager, and employee

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/profile-picture.png"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
